# Generated by Django 5.0.1 on 2024-01-18 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=255)),
                ('codRol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Empresario',
            fields=[
                ('idEmpresario', models.AutoField(primary_key=True, serialize=False)),
                ('RazonSocial', models.CharField(max_length=255)),
                ('DescripcionEstablecimientos', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('Usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
            ],
        ),
    ]
