# Generated by Django 5.0.1 on 2024-02-29 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenPerfil',
            fields=[
                ('codImagenPerfil', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='imagenes_perfil/')),
            ],
        ),
    ]
