# Generated by Django 5.0.1 on 2024-01-18 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresario',
            old_name='DescripcionEstablecimientos',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña',
            new_name='clave',
        ),
    ]
