# Generated by Django 5.0.1 on 2024-02-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metododepago',
            name='codMetodoDePago',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
