# Generated by Django 5.0.1 on 2024-03-07 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_comentario_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='turista',
            name='codImagenPerfil',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, to='users.imagenperfil'),
        ),
    ]
