# Generated by Django 5.0.1 on 2024-02-29 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_imagenperfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='turista',
            name='codImagenPerfil',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.imagenperfil'),
        ),
    ]
