# Generated by Django 5.0.1 on 2024-02-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_comercio_codcomercio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comercio',
            name='codTipoComercio',
        ),
        migrations.AddField(
            model_name='comercio',
            name='codTipoComercio',
            field=models.ManyToManyField(related_name='TipoComercio', to='users.tipocomercio'),
        ),
    ]
