# Generated by Django 5.0.1 on 2024-03-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_turista_codimagenperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='descripcion',
            field=models.TextField(default='Sin descripcion', max_length=1000),
        ),
    ]
