# Generated by Django 5.0.1 on 2024-01-29 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_razonsocial_empresario_razonsocial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresario',
            old_name='Usuario',
            new_name='usuario',
        ),
    ]
