# Generated by Django 5.0.1 on 2024-01-29 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_usuario_empresario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresario', to='users.usuario'),
        ),
    ]
