# Generated by Django 5.0.1 on 2024-03-08 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_turista_codimagenperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='descripcion',
            field=models.TextField(default='Sin descripcion', max_length=1000),
        ),
        migrations.AlterField(
            model_name='turista',
            name='codImagenPerfil',
            field=models.OneToOneField(default=5, on_delete=django.db.models.deletion.CASCADE, to='users.imagenperfil'),
        ),
    ]
