# Generated by Django 5.0.1 on 2024-01-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_empresario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nombreUsuario',
            field=models.CharField(default='username', max_length=255, unique=True),
        ),
    ]
