# Generated by Django 5.0.1 on 2024-02-01 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_usuario_codrol_remove_empresario_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('codHorario', models.AutoField(primary_key=True, serialize=False)),
                ('horaApertura', models.TimeField()),
                ('horaCierre', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('codImagen', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='MetodoDePago',
            fields=[
                ('codMetodoDePago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('codRedSocial', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('codTelefono', models.AutoField(primary_key=True, serialize=False)),
                ('horaApertura', models.TimeField()),
                ('horaCierre', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoEstablecimiento',
            fields=[
                ('codTipoEstablecimiento', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('calificacionPromedio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('codEstablecimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('calle', models.CharField(max_length=255)),
                ('altura', models.IntegerField()),
                ('empresario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.empresario')),
                ('codHorario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.horario')),
                ('codTelefono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.telefono')),
                ('tipoEstablecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tipoestablecimiento')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenXEstablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codEstablecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.establecimiento')),
                ('codImagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.imagen')),
            ],
        ),
        migrations.CreateModel(
            name='EstablecimientoXMetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codEstablecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.establecimiento')),
                ('codMetodoDePago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.metododepago')),
            ],
        ),
        migrations.CreateModel(
            name='EstablecimientoXRedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codEstablecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.establecimiento')),
                ('codRedSocial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.redsocial')),
            ],
        ),
    ]
