# Generated by Django 5.0.1 on 2024-02-01 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_horario_imagen_metododepago_redsocial_telefono_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAlojamiento',
            fields=[
                ('codTipoAlojamiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('codTipoServicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Alojamiento',
            fields=[
                ('codAlojamiento', models.AutoField(primary_key=True, serialize=False)),
                ('codEstablecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.establecimiento')),
                ('codTipoAlojamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tipoalojamiento')),
                ('codTipoServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tiposervicio')),
            ],
        ),
        migrations.CreateModel(
            name='AlojamientoXTipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codAlojamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.alojamiento')),
                ('codTipoServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tiposervicio')),
            ],
        ),
    ]
