# Generated by Django 5.0.1 on 2024-02-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_tipoalojamiento_tiposervicio_alojamiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoestablecimiento',
            name='calificacionPromedio',
        ),
        migrations.RemoveField(
            model_name='tipoestablecimiento',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='tipoestablecimiento',
            name='nombre',
            field=models.CharField(default='nombre', max_length=255),
        ),
    ]
