# Generated by Django 5.0.1 on 2024-03-11 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_establecimiento_descripcion'),
        ('users', '0011_alter_turista_codimagenperfil'),
    ]

    operations = [
    ]
