# Generated by Django 5.0.1 on 2024-02-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_tipoestablecimiento_calificacionpromedio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimientoxredsocial',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
