# Generated by Django 5.0.1 on 2024-03-11 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_merge_20240310_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turista',
            name='codImagenPerfil',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='users.imagenperfil'),
        ),
    ]
