# Generated by Django 5.0.1 on 2024-02-05 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_categoria_alojamiento_codcategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamiento',
            name='codCategoria',
            field=models.ForeignKey(default='Sin Categoría', on_delete=django.db.models.deletion.CASCADE, to='users.categoria'),
        ),
    ]
