# Generated by Django 5.0.1 on 2024-02-05 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_alojamiento_codcategoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
