# Generated by Django 5.0.1 on 2024-02-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_alojamiento_codcategoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alojamiento',
            old_name='codCategoria',
            new_name='codCat',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
