# Generated by Django 5.0.1 on 2024-02-05 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_rename_codcategoria_alojamiento_codcat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alojamiento',
            name='codCat',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
