# Generated by Django 5.0.1 on 2024-02-05 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_alojamiento_codcat_delete_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establecimientoxredsocial',
            name='url',
        ),
        migrations.AlterField(
            model_name='tipoestablecimiento',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
