# Generated by Django 5.0.1 on 2024-02-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_categoria_alojamiento_codcategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redsocial',
            name='nombre',
            field=models.CharField(default='Sin categoria', max_length=255),
        ),
    ]
