# Generated by Django 5.0.1 on 2024-02-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_redsocial_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redsocial',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
