<<<<<<< HEAD
# Generated by Django 5.0.1 on 2024-02-06 18:24
=======
# Generated by Django 5.0.1 on 2024-02-06 18:46
>>>>>>> f63a73c1ab0c807bec5e5683cc01fddb76e3f95e

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_ciudad_pais_establecimiento_codciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='codProvincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.provincia'),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='codCiudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ciudad'),
        ),
    ]
