# Generated by Django 5.0.1 on 2024-02-06 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_ciudad_codprovincia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alojamientos',
            fields=[
                ('establecimiento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='users.establecimiento')),
                ('codAlojamiento', models.AutoField(primary_key=True, serialize=False)),
                ('codCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.categoria')),
                ('codTipoAlojamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tipoalojamiento')),
                ('codTipoServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tiposervicio')),
            ],
            bases=('users.establecimiento',),
        ),
        migrations.AlterField(
            model_name='alojamientoxtiposervicio',
            name='codAlojamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.alojamientos'),
        ),
        migrations.DeleteModel(
            name='Alojamiento',
        ),
    ]
