# Generated by Django 5.0.1 on 2024-02-07 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_establecimiento_metodos_de_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenxestablecimiento',
            name='codImagen',
        ),
        migrations.RemoveField(
            model_name='imagenxestablecimiento',
            name='codEstablecimiento',
        ),
        migrations.AlterField(
            model_name='metododepago',
            name='codMetodoDePago',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='metododepago',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('codImagen', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='imagenes_establecimiento/')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='users.establecimiento')),
            ],
        ),
        migrations.DeleteModel(
            name='EstablecimientoXRedSocial',
        ),
        migrations.DeleteModel(
            name='RedSocial',
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
        migrations.DeleteModel(
            name='ImagenXEstablecimiento',
        ),
    ]
