# Generated by Django 5.0.1 on 2024-02-07 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_remove_imagenxestablecimiento_codimagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alojamientos',
            name='codTipoServicio',
        ),
        migrations.AddField(
            model_name='alojamientos',
            name='servicios',
            field=models.ManyToManyField(related_name='alojamientos', to='users.tiposervicio'),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='empresario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establecimientos', to='users.empresario'),
        ),
        migrations.DeleteModel(
            name='AlojamientoXTipoServicio',
        ),
    ]
