# Generated by Django 5.0.1 on 2024-02-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_remove_alojamientos_codtiposervicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='codTelefono',
            field=models.IntegerField(),
        ),
    ]
