# Generated by Django 5.0.1 on 2024-02-07 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_rename_codtelefono_establecimiento_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alojamientos',
            name='codAlojamiento',
        ),
        migrations.AlterField(
            model_name='alojamientos',
            name='establecimiento_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.establecimiento'),
        ),
    ]
