# Generated by Django 5.0.1 on 2024-02-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_remove_alojamientos_codalojamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='descripcion',
            field=models.TextField(default='Sin descripcion', max_length=255),
        ),
    ]
