# Generated by Django 5.0.1 on 2024-02-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_establecimiento_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='altura',
            field=models.CharField(max_length=255),
        ),
    ]
