# Generated by Django 5.0.1 on 2024-02-07 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_alter_establecimiento_altura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establecimiento',
            name='altura',
        ),
    ]
