# Generated by Django 5.0.1 on 2024-02-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_remove_establecimiento_altura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='telefono',
            field=models.CharField(max_length=255),
        ),
    ]
