# Generated by Django 5.0.1 on 2024-02-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_alter_establecimiento_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='altura',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
