# Generated by Django 5.0.1 on 2024-02-08 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_establecimiento_altura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenes',
            name='establecimiento',
        ),
        migrations.AddField(
            model_name='imagenes',
            name='alojamiento',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='users.alojamientos'),
        ),
    ]
