# Generated by Django 5.0.1 on 2024-02-08 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_remove_imagenes_establecimiento_imagenes_alojamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes_establecimiento/')),
                ('alojamiento', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='users.alojamientos')),
            ],
        ),
        migrations.DeleteModel(
            name='Imagenes',
        ),
    ]
