# Generated by Django 5.0.1 on 2024-02-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_imagen_delete_imagenes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Telefono',
        ),
        migrations.AlterField(
            model_name='horario',
            name='horaApertura',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='horario',
            name='horaCierre',
            field=models.CharField(max_length=255),
        ),
    ]
