# Generated by Django 5.0.1 on 2024-02-08 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_delete_telefono_alter_horario_horaapertura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='alojamiento',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='users.establecimiento'),
        ),
    ]
