# Generated by Django 5.0.1 on 2024-02-09 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_alter_imagen_alojamiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagen',
            old_name='alojamiento',
            new_name='establecimiento',
        ),
    ]
