# Generated by Django 5.0.1 on 2024-02-26 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_alter_imagen_alojamiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoComercio',
            fields=[
                ('codTipoComercio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoComida',
            fields=[
                ('codTipoComida', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoGastronomia',
            fields=[
                ('codTipoGastronomia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPrefAliment',
            fields=[
                ('codTipoPrefAliment', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoServGastro',
            fields=[
                ('codTipoServGastro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='imagen',
            old_name='alojamiento',
            new_name='establecimiento',
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('codComentario', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField(max_length=500)),
                ('calificacion', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.establecimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('establecimiento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='users.establecimiento')),
                ('codComercio', models.AutoField(primary_key=True, serialize=False)),
                ('codTipoComercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tipocomercio')),
            ],
            bases=('users.establecimiento',),
        ),
        migrations.CreateModel(
            name='Gastronomia',
            fields=[
                ('establecimiento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='users.establecimiento')),
                ('codGastronomia', models.AutoField(primary_key=True, serialize=False)),
                ('tipos_comida', models.ManyToManyField(related_name='Gastronomia', to='users.tipocomida')),
                ('tipos_gastronomia', models.ManyToManyField(related_name='Gastronomia', to='users.tipogastronomia')),
                ('tipos_pref_alimentaria', models.ManyToManyField(related_name='Gastronomia', to='users.tipoprefaliment')),
                ('tipos_servicio_gastronomico', models.ManyToManyField(related_name='Gastronomia', to='users.tiposervgastro')),
            ],
            bases=('users.establecimiento',),
        ),
        migrations.CreateModel(
            name='Turista',
            fields=[
                ('codTurista', models.AutoField(primary_key=True, serialize=False)),
                ('comentarios', models.ManyToManyField(blank=True, related_name='turista_comentarios', to='users.comentario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comentario',
            name='turista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_turista', to='users.turista'),
        ),
    ]
