# Generated by Django 5.0.1 on 2024-02-21 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_rename_alojamiento_imagen_establecimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoComida',
            fields=[
                ('codTipoComida', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoGastronomia',
            fields=[
                ('codTipoGastronomia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPrefAliment',
            fields=[
                ('codTipoPrefAliment', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoServGastro',
            fields=[
                ('codTipoServGastro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gastronomia',
            fields=[
                ('establecimiento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='users.establecimiento')),
                ('codGastronomia', models.AutoField(primary_key=True, serialize=False)),
                ('codCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.categoria')),
                ('tipos_comida', models.ManyToManyField(related_name='Gastronomia', to='users.tipocomida')),
                ('tipos_gastronomia', models.ManyToManyField(related_name='Gastronomia', to='users.tipogastronomia')),
                ('tipos_pref_alimentaria', models.ManyToManyField(related_name='Gastronomia', to='users.tipoprefaliment')),
                ('tipos_servicio_gastronomico', models.ManyToManyField(related_name='Gastronomia', to='users.tiposervgastro')),
            ],
            bases=('users.establecimiento',),
        ),
    ]
