# Generated by Django 5.0.1 on 2024-02-21 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_tipocomida_tipogastronomia_tipoprefaliment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gastronomia',
            name='codCategoria',
        ),
    ]
