# Generated by Django 5.0.1 on 2024-02-22 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_tipocomida_tipogastronomia_tipoprefaliment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoComercio',
            fields=[
                ('codTipoComercio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('establecimiento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='users.establecimiento')),
                ('codComercio', models.AutoField(primary_key=True, serialize=False)),
                ('codTipoComercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tipocomercio')),
            ],
            bases=('users.establecimiento',),
        ),
    ]
