# Generated by Django 5.0.1 on 2024-02-24 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_remove_gastronomia_codcategoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('codComentario', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField(max_length=500)),
                ('calificacion', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.establecimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Turista',
            fields=[
                ('codTurista', models.AutoField(primary_key=True, serialize=False)),
                ('comentarios', models.ManyToManyField(blank=True, related_name='turista_comentarios', to='users.comentario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comentario',
            name='turista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_turista', to='users.turista'),
        ),
    ]
